# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "David Metanfanuan Jr"
description: > # this means to ignore newlines until "email:"
   A Data Science Student in Airlangga University

email: david.aristotle21@gmail.com
#blog logo
logo: "download (2).png"
float_logo: false # true, false (default)

# blog cover
cover: "wallpaperflare.com_wallpaper2.jpg"

name: 'David Metanfanuan Jr'
author: 'David Metanfanuan Jr'
author_image: 'author.jpg'

paginate:	3

# url: "oceannbreezq.github.io" # the base hostname & protocol for your site
# baseurl: "oceannbreezq.github.io"
# # #used to display twitter cards
# twitter_handle: '@gwooddevil'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	envelope
    url:	david.aristotle21@gmail.com
    share_url:
    share_title:
    share_link:

  - icon:	instagram
    url:	https://instagram.com/davidmetanjr
    desc: Follow me on Instagram
    share_url: 
    share_title:
    share_link: 

  - icon:	github
    url:	https://github.com/oceannbreezq/
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
